version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 25
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: false
  identical-code:
    config:
      threshold: false

## excluded from all tests, analyses
exclude_patterns:
- ".cicd/"
- "./.cicd/"

plugins:
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
      file_extensions: "php,inc,lib"
  sonar-php:
    enabled: true
    config:
      minimum_severity: major
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
